#!/bin/bash

# JankyBorders configuration using Herdr's Catppuccin Macchiato palette.
options=(
  style=round
  width=2.0
  hidpi=on
  active_color=0xff8aadf4
  inactive_color=0xff363a4f
)

borders "${options[@]}"
