gui:
  showBottomLine: true 
  showCommandLog: false
  showFileTree: false
  border: single
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    selectedLineBgColor:
      - '#363a4f'

git:
  branchLogCmd: "git log --graph --color=always --oneline {{branchName}} --"
  commit:
    signOff: true
  pagers:
    - externalDiffCommand: hunk diff
