#!/bin/bash

set -u

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
PLUGIN_DIR="$CONFIG_DIR/plugins"
# shellcheck source=/dev/null
source "$CONFIG_DIR/colors.sh"

sketchybar --bar \
  position=top \
  height=32 \
  padding_left=8 \
  padding_right=8 \
  color="$BASE" \
  blur_radius=0

default=(
  padding_left=6
  padding_right=6
  icon.drawing=off
  label.font="SF Pro:Semibold:13.0"
  label.color="$TEXT"
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6 7 8 9; do
  sketchybar --add item "space.$sid" left \
    --set "space.$sid" \
      label="$sid" \
      background.drawing=off \
      background.color="$SURFACE0" \
      background.corner_radius=6 \
      background.height=24 \
      script="$PLUGIN_DIR/aerospace_workspace.sh" \
      click_script="aerospace workspace $sid" \
    --subscribe "space.$sid" aerospace_workspace_change
 done

sketchybar --add item front_app left \
  --set front_app \
    label="" \
    label.max_chars=32 \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item volume right \
  --set volume \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery \
    update_freq=120 \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --update
