# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Needs Review
    filters: is:open review-requested:@me
  - title: My PRs
    filters: is:open author:@me
  - title: All Involved PRs
    filters: is:open involves:@me
  - title: All PRs
    filters: is:open

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention

defaults:
  view: prs
  refetchIntervalMinutes: 5
  preview:
    open: true

theme:
  colors:
    text:
      primary: '#cad3f5'
      secondary: '#b8c0e0'
      inverted: '#24273a'
      faint: '#6e738d'
      warning: '#f5a97f'
      success: '#a6da95'
    background:
      selected: '#363a4f'
    border:
      primary: '#8aadf4'
      secondary: '#494d64'
      faint: '#363a4f'

pager:
  diff: diffnav
