#!/usr/bin/env bash
#MISE description="List all unused branches in the current repository."
#MISE dir="{{cwd}}"
#MISE alias="glub"
set -euo pipefail

git branch -vv | grep ': gone]' | awk '{print $1}'
