#!/usr/bin/env bash
#MISE description="Delete all unused branches in the current repository."
#MISE dir="{{cwd}}"
#MISE alias="gdub"
set -euo pipefail

git branch -vv | awk '/: gone]/{print $1}' | while read -r branch; do
  [ -n "$branch" ] && git branch -D "$branch"
done
