[env]
AWS_VAULT_KEYCHAIN_NAME = "login"
AWS_VAULT_BACKEND = "keychain"

[tasks."aws-vault:refresh"]
alias = "avr"
description = "Print AWS Vault environment exports for the current shell"
run = "AWS_VAULT= aws-vault export --format=export-env \"$AWS_VAULT\""
