[env]
AWS_VAULT_KEYCHAIN_NAME = "login"
AWS_VAULT_BACKEND = "keychain"

[tasks."aws-vault:refresh"]
alias = "avr"
description = "Refresh credentials in `aws-vault` subshell"
run = "eval $(AWS_VAULT= aws-vault export --format=export-env $AWS_VAULT)"
